[package]
name = "xqr-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwtk = "0.2.4"
axum = "0.6.20"
tokio = { version = "1.30.0", features = ["full"] }
serde = "1.0.183"
